// Autogenerated from Pigeon (v29.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

enum NativeLayerShellLayer { background, bottom, top, overlay }

enum NativeLayerShellKeyboardMode { none, exclusive, onDemand }

enum NativeLayerShellBarEdge { top, bottom }

enum NativeLayerShellMonitorTargetKind { primary, all, named, hidden }

class NativeLayerShellMonitorTarget {
  NativeLayerShellMonitorTarget({required this.kind, this.name});

  NativeLayerShellMonitorTargetKind kind;

  String? name;

  List<Object?> _toList() {
    return <Object?>[kind, name];
  }

  Object encode() {
    return _toList();
  }

  static NativeLayerShellMonitorTarget decode(Object result) {
    result as List<Object?>;
    return NativeLayerShellMonitorTarget(
      kind: result[0]! as NativeLayerShellMonitorTargetKind,
      name: result[1] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeLayerShellMonitorTarget ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(kind, other.kind) && _deepEquals(name, other.name);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeLayerShellMonitorTarget(kind: $kind, name: $name)';
  }
}

class NativeLayerShellMonitor {
  NativeLayerShellMonitor({
    required this.name,
    required this.label,
    required this.isPrimary,
    required this.x,
    required this.y,
    required this.width,
    required this.height,
    required this.refreshRateMillihertz,
  });

  String name;

  String label;

  bool isPrimary;

  int x;

  int y;

  int width;

  int height;

  int refreshRateMillihertz;

  List<Object?> _toList() {
    return <Object?>[
      name,
      label,
      isPrimary,
      x,
      y,
      width,
      height,
      refreshRateMillihertz,
    ];
  }

  Object encode() {
    return _toList();
  }

  static NativeLayerShellMonitor decode(Object result) {
    result as List<Object?>;
    return NativeLayerShellMonitor(
      name: result[0]! as String,
      label: result[1]! as String,
      isPrimary: result[2]! as bool,
      x: result[3]! as int,
      y: result[4]! as int,
      width: result[5]! as int,
      height: result[6]! as int,
      refreshRateMillihertz: result[7]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeLayerShellMonitor || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(name, other.name) &&
        _deepEquals(label, other.label) &&
        _deepEquals(isPrimary, other.isPrimary) &&
        _deepEquals(x, other.x) &&
        _deepEquals(y, other.y) &&
        _deepEquals(width, other.width) &&
        _deepEquals(height, other.height) &&
        _deepEquals(refreshRateMillihertz, other.refreshRateMillihertz);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeLayerShellMonitor(name: $name, label: $label, isPrimary: $isPrimary, x: $x, y: $y, width: $width, height: $height, refreshRateMillihertz: $refreshRateMillihertz)';
  }
}

class NativeLayerShellAnchors {
  NativeLayerShellAnchors({this.top, this.bottom, this.left, this.right});

  bool? top;

  bool? bottom;

  bool? left;

  bool? right;

  List<Object?> _toList() {
    return <Object?>[top, bottom, left, right];
  }

  Object encode() {
    return _toList();
  }

  static NativeLayerShellAnchors decode(Object result) {
    result as List<Object?>;
    return NativeLayerShellAnchors(
      top: result[0] as bool?,
      bottom: result[1] as bool?,
      left: result[2] as bool?,
      right: result[3] as bool?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeLayerShellAnchors || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(top, other.top) &&
        _deepEquals(bottom, other.bottom) &&
        _deepEquals(left, other.left) &&
        _deepEquals(right, other.right);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeLayerShellAnchors(top: $top, bottom: $bottom, left: $left, right: $right)';
  }
}

class NativeLayerShellMargins {
  NativeLayerShellMargins({this.top, this.bottom, this.left, this.right});

  int? top;

  int? bottom;

  int? left;

  int? right;

  List<Object?> _toList() {
    return <Object?>[top, bottom, left, right];
  }

  Object encode() {
    return _toList();
  }

  static NativeLayerShellMargins decode(Object result) {
    result as List<Object?>;
    return NativeLayerShellMargins(
      top: result[0] as int?,
      bottom: result[1] as int?,
      left: result[2] as int?,
      right: result[3] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeLayerShellMargins || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(top, other.top) &&
        _deepEquals(bottom, other.bottom) &&
        _deepEquals(left, other.left) &&
        _deepEquals(right, other.right);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeLayerShellMargins(top: $top, bottom: $bottom, left: $left, right: $right)';
  }
}

class NativeLayerShellSize {
  NativeLayerShellSize({this.width, this.height});

  int? width;

  int? height;

  List<Object?> _toList() {
    return <Object?>[width, height];
  }

  Object encode() {
    return _toList();
  }

  static NativeLayerShellSize decode(Object result) {
    result as List<Object?>;
    return NativeLayerShellSize(
      width: result[0] as int?,
      height: result[1] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeLayerShellSize || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(width, other.width) && _deepEquals(height, other.height);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeLayerShellSize(width: $width, height: $height)';
  }
}

class NativeLayerShellRegion {
  NativeLayerShellRegion({
    required this.x,
    required this.y,
    required this.width,
    required this.height,
    required this.radiusTopLeft,
    required this.radiusTopRight,
    required this.radiusBottomRight,
    required this.radiusBottomLeft,
  });

  int x;

  int y;

  int width;

  int height;

  int radiusTopLeft;

  int radiusTopRight;

  int radiusBottomRight;

  int radiusBottomLeft;

  List<Object?> _toList() {
    return <Object?>[
      x,
      y,
      width,
      height,
      radiusTopLeft,
      radiusTopRight,
      radiusBottomRight,
      radiusBottomLeft,
    ];
  }

  Object encode() {
    return _toList();
  }

  static NativeLayerShellRegion decode(Object result) {
    result as List<Object?>;
    return NativeLayerShellRegion(
      x: result[0]! as int,
      y: result[1]! as int,
      width: result[2]! as int,
      height: result[3]! as int,
      radiusTopLeft: result[4]! as int,
      radiusTopRight: result[5]! as int,
      radiusBottomRight: result[6]! as int,
      radiusBottomLeft: result[7]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeLayerShellRegion || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(x, other.x) &&
        _deepEquals(y, other.y) &&
        _deepEquals(width, other.width) &&
        _deepEquals(height, other.height) &&
        _deepEquals(radiusTopLeft, other.radiusTopLeft) &&
        _deepEquals(radiusTopRight, other.radiusTopRight) &&
        _deepEquals(radiusBottomRight, other.radiusBottomRight) &&
        _deepEquals(radiusBottomLeft, other.radiusBottomLeft);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeLayerShellRegion(x: $x, y: $y, width: $width, height: $height, radiusTopLeft: $radiusTopLeft, radiusTopRight: $radiusTopRight, radiusBottomRight: $radiusBottomRight, radiusBottomLeft: $radiusBottomLeft)';
  }
}

class NativeLayerShellRegionRequest {
  NativeLayerShellRegionRequest({
    required this.barHeight,
    required this.barEdge,
    this.menu,
    required this.passiveRegions,
    required this.captureAllClicks,
  });

  int barHeight;

  NativeLayerShellBarEdge barEdge;

  NativeLayerShellRegion? menu;

  List<NativeLayerShellRegion> passiveRegions;

  bool captureAllClicks;

  List<Object?> _toList() {
    return <Object?>[
      barHeight,
      barEdge,
      menu,
      passiveRegions,
      captureAllClicks,
    ];
  }

  Object encode() {
    return _toList();
  }

  static NativeLayerShellRegionRequest decode(Object result) {
    result as List<Object?>;
    return NativeLayerShellRegionRequest(
      barHeight: result[0]! as int,
      barEdge: result[1]! as NativeLayerShellBarEdge,
      menu: result[2] as NativeLayerShellRegion?,
      passiveRegions: (result[3]! as List<Object?>)
          .cast<NativeLayerShellRegion>(),
      captureAllClicks: result[4]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeLayerShellRegionRequest ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(barHeight, other.barHeight) &&
        _deepEquals(barEdge, other.barEdge) &&
        _deepEquals(menu, other.menu) &&
        _deepEquals(passiveRegions, other.passiveRegions) &&
        _deepEquals(captureAllClicks, other.captureAllClicks);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeLayerShellRegionRequest(barHeight: $barHeight, barEdge: $barEdge, menu: $menu, passiveRegions: $passiveRegions, captureAllClicks: $captureAllClicks)';
  }
}

class NativeLayerShellPanelConfig {
  NativeLayerShellPanelConfig({
    required this.appNamespace,
    required this.layer,
    required this.anchors,
    required this.margins,
    required this.size,
    required this.exclusiveZone,
    required this.autoExclusiveZone,
    required this.keyboardMode,
    required this.monitor,
  });

  String appNamespace;

  NativeLayerShellLayer layer;

  NativeLayerShellAnchors anchors;

  NativeLayerShellMargins margins;

  NativeLayerShellSize size;

  int exclusiveZone;

  bool autoExclusiveZone;

  NativeLayerShellKeyboardMode keyboardMode;

  NativeLayerShellMonitorTarget monitor;

  List<Object?> _toList() {
    return <Object?>[
      appNamespace,
      layer,
      anchors,
      margins,
      size,
      exclusiveZone,
      autoExclusiveZone,
      keyboardMode,
      monitor,
    ];
  }

  Object encode() {
    return _toList();
  }

  static NativeLayerShellPanelConfig decode(Object result) {
    result as List<Object?>;
    return NativeLayerShellPanelConfig(
      appNamespace: result[0]! as String,
      layer: result[1]! as NativeLayerShellLayer,
      anchors: result[2]! as NativeLayerShellAnchors,
      margins: result[3]! as NativeLayerShellMargins,
      size: result[4]! as NativeLayerShellSize,
      exclusiveZone: result[5]! as int,
      autoExclusiveZone: result[6]! as bool,
      keyboardMode: result[7]! as NativeLayerShellKeyboardMode,
      monitor: result[8]! as NativeLayerShellMonitorTarget,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeLayerShellPanelConfig ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(appNamespace, other.appNamespace) &&
        _deepEquals(layer, other.layer) &&
        _deepEquals(anchors, other.anchors) &&
        _deepEquals(margins, other.margins) &&
        _deepEquals(size, other.size) &&
        _deepEquals(exclusiveZone, other.exclusiveZone) &&
        _deepEquals(autoExclusiveZone, other.autoExclusiveZone) &&
        _deepEquals(keyboardMode, other.keyboardMode) &&
        _deepEquals(monitor, other.monitor);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeLayerShellPanelConfig(appNamespace: $appNamespace, layer: $layer, anchors: $anchors, margins: $margins, size: $size, exclusiveZone: $exclusiveZone, autoExclusiveZone: $autoExclusiveZone, keyboardMode: $keyboardMode, monitor: $monitor)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is NativeLayerShellLayer) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is NativeLayerShellKeyboardMode) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is NativeLayerShellBarEdge) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    } else if (value is NativeLayerShellMonitorTargetKind) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    } else if (value is NativeLayerShellMonitorTarget) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is NativeLayerShellMonitor) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is NativeLayerShellAnchors) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is NativeLayerShellMargins) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else if (value is NativeLayerShellSize) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else if (value is NativeLayerShellRegion) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    } else if (value is NativeLayerShellRegionRequest) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    } else if (value is NativeLayerShellPanelConfig) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : NativeLayerShellLayer.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null
            ? null
            : NativeLayerShellKeyboardMode.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : NativeLayerShellBarEdge.values[value];
      case 132:
        final value = readValue(buffer) as int?;
        return value == null
            ? null
            : NativeLayerShellMonitorTargetKind.values[value];
      case 133:
        return NativeLayerShellMonitorTarget.decode(readValue(buffer)!);
      case 134:
        return NativeLayerShellMonitor.decode(readValue(buffer)!);
      case 135:
        return NativeLayerShellAnchors.decode(readValue(buffer)!);
      case 136:
        return NativeLayerShellMargins.decode(readValue(buffer)!);
      case 137:
        return NativeLayerShellSize.decode(readValue(buffer)!);
      case 138:
        return NativeLayerShellRegion.decode(readValue(buffer)!);
      case 139:
        return NativeLayerShellRegionRequest.decode(readValue(buffer)!);
      case 140:
        return NativeLayerShellPanelConfig.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class NativeLayerShellHostApi {
  /// Constructor for [NativeLayerShellHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  NativeLayerShellHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<List<NativeLayerShellMonitor>> listMonitors() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hyprbaric.NativeLayerShellHostApi.listMonitors$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>)
        .cast<NativeLayerShellMonitor>();
  }

  Future<NativeLayerShellMonitor?> currentMonitor() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hyprbaric.NativeLayerShellHostApi.currentMonitor$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as NativeLayerShellMonitor?;
  }

  Future<void> configurePanel(NativeLayerShellPanelConfig config) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hyprbaric.NativeLayerShellHostApi.configurePanel$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[config],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> setLayer(NativeLayerShellLayer layer) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hyprbaric.NativeLayerShellHostApi.setLayer$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[layer],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> setNamespace(String appNamespace) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hyprbaric.NativeLayerShellHostApi.setNamespace$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[appNamespace],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> setAnchors(NativeLayerShellAnchors anchors) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hyprbaric.NativeLayerShellHostApi.setAnchors$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[anchors],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> setMargins(NativeLayerShellMargins margins) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hyprbaric.NativeLayerShellHostApi.setMargins$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[margins],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> setExclusiveZone(int zone) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hyprbaric.NativeLayerShellHostApi.setExclusiveZone$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[zone],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> setAutoExclusiveZone(bool enabled) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hyprbaric.NativeLayerShellHostApi.setAutoExclusiveZone$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[enabled],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> setKeyboardMode(NativeLayerShellKeyboardMode mode) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hyprbaric.NativeLayerShellHostApi.setKeyboardMode$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[mode],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> setSize(NativeLayerShellSize size) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hyprbaric.NativeLayerShellHostApi.setSize$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[size],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> setRegion(NativeLayerShellRegionRequest request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.hyprbaric.NativeLayerShellHostApi.setRegion$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }
}
