// Autogenerated from Pigeon (v29.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_LAYER_SHELL_API_G_H_
#define PIGEON_LAYER_SHELL_API_G_H_

#include <flutter_linux/flutter_linux.h>

G_BEGIN_DECLS

/**
 * HyprbaricNativeLayerShellLayer:
 * HYPRBARIC_NATIVE_LAYER_SHELL_LAYER_BACKGROUND:
 * HYPRBARIC_NATIVE_LAYER_SHELL_LAYER_BOTTOM:
 * HYPRBARIC_NATIVE_LAYER_SHELL_LAYER_TOP:
 * HYPRBARIC_NATIVE_LAYER_SHELL_LAYER_OVERLAY:
 *
 */
typedef enum {
  HYPRBARIC_NATIVE_LAYER_SHELL_LAYER_BACKGROUND = 0,
  HYPRBARIC_NATIVE_LAYER_SHELL_LAYER_BOTTOM = 1,
  HYPRBARIC_NATIVE_LAYER_SHELL_LAYER_TOP = 2,
  HYPRBARIC_NATIVE_LAYER_SHELL_LAYER_OVERLAY = 3
} HyprbaricNativeLayerShellLayer;

/**
 * HyprbaricNativeLayerShellKeyboardMode:
 * HYPRBARIC_NATIVE_LAYER_SHELL_KEYBOARD_MODE_NONE:
 * HYPRBARIC_NATIVE_LAYER_SHELL_KEYBOARD_MODE_EXCLUSIVE:
 * HYPRBARIC_NATIVE_LAYER_SHELL_KEYBOARD_MODE_ON_DEMAND:
 *
 */
typedef enum {
  HYPRBARIC_NATIVE_LAYER_SHELL_KEYBOARD_MODE_NONE = 0,
  HYPRBARIC_NATIVE_LAYER_SHELL_KEYBOARD_MODE_EXCLUSIVE = 1,
  HYPRBARIC_NATIVE_LAYER_SHELL_KEYBOARD_MODE_ON_DEMAND = 2
} HyprbaricNativeLayerShellKeyboardMode;

/**
 * HyprbaricNativeLayerShellBarEdge:
 * HYPRBARIC_NATIVE_LAYER_SHELL_BAR_EDGE_TOP:
 * HYPRBARIC_NATIVE_LAYER_SHELL_BAR_EDGE_BOTTOM:
 *
 */
typedef enum {
  HYPRBARIC_NATIVE_LAYER_SHELL_BAR_EDGE_TOP = 0,
  HYPRBARIC_NATIVE_LAYER_SHELL_BAR_EDGE_BOTTOM = 1
} HyprbaricNativeLayerShellBarEdge;

/**
 * HyprbaricNativeLayerShellMonitorTargetKind:
 * HYPRBARIC_NATIVE_LAYER_SHELL_MONITOR_TARGET_KIND_PRIMARY:
 * HYPRBARIC_NATIVE_LAYER_SHELL_MONITOR_TARGET_KIND_ALL:
 * HYPRBARIC_NATIVE_LAYER_SHELL_MONITOR_TARGET_KIND_NAMED:
 * HYPRBARIC_NATIVE_LAYER_SHELL_MONITOR_TARGET_KIND_HIDDEN:
 *
 */
typedef enum {
  HYPRBARIC_NATIVE_LAYER_SHELL_MONITOR_TARGET_KIND_PRIMARY = 0,
  HYPRBARIC_NATIVE_LAYER_SHELL_MONITOR_TARGET_KIND_ALL = 1,
  HYPRBARIC_NATIVE_LAYER_SHELL_MONITOR_TARGET_KIND_NAMED = 2,
  HYPRBARIC_NATIVE_LAYER_SHELL_MONITOR_TARGET_KIND_HIDDEN = 3
} HyprbaricNativeLayerShellMonitorTargetKind;

/**
 * HyprbaricNativeLayerShellMonitorTarget:
 *
 */

G_DECLARE_FINAL_TYPE(HyprbaricNativeLayerShellMonitorTarget, hyprbaric_native_layer_shell_monitor_target, HYPRBARIC, NATIVE_LAYER_SHELL_MONITOR_TARGET, GObject)

/**
 * hyprbaric_native_layer_shell_monitor_target_new:
 * kind: field in this object.
 * name: field in this object.
 *
 * Creates a new #NativeLayerShellMonitorTarget object.
 *
 * Returns: a new #HyprbaricNativeLayerShellMonitorTarget
 */
HyprbaricNativeLayerShellMonitorTarget* hyprbaric_native_layer_shell_monitor_target_new(HyprbaricNativeLayerShellMonitorTargetKind kind, const gchar* name);

/**
 * hyprbaric_native_layer_shell_monitor_target_get_kind
 * @object: a #HyprbaricNativeLayerShellMonitorTarget.
 *
 * Gets the value of the kind field of @object.
 *
 * Returns: the field value.
 */
HyprbaricNativeLayerShellMonitorTargetKind hyprbaric_native_layer_shell_monitor_target_get_kind(HyprbaricNativeLayerShellMonitorTarget* object);

/**
 * hyprbaric_native_layer_shell_monitor_target_get_name
 * @object: a #HyprbaricNativeLayerShellMonitorTarget.
 *
 * Gets the value of the name field of @object.
 *
 * Returns: the field value.
 */
const gchar* hyprbaric_native_layer_shell_monitor_target_get_name(HyprbaricNativeLayerShellMonitorTarget* object);

/**
 * hyprbaric_native_layer_shell_monitor_target_equals:
 * @a: a #HyprbaricNativeLayerShellMonitorTarget.
 * @b: another #HyprbaricNativeLayerShellMonitorTarget.
 *
 * Checks if two #HyprbaricNativeLayerShellMonitorTarget objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean hyprbaric_native_layer_shell_monitor_target_equals(HyprbaricNativeLayerShellMonitorTarget* a, HyprbaricNativeLayerShellMonitorTarget* b);

/**
 * hyprbaric_native_layer_shell_monitor_target_hash:
 * @object: a #HyprbaricNativeLayerShellMonitorTarget.
 *
 * Calculates a hash code for a #HyprbaricNativeLayerShellMonitorTarget object.
 *
 * Returns: the hash code.
 */
guint hyprbaric_native_layer_shell_monitor_target_hash(HyprbaricNativeLayerShellMonitorTarget* object);

/**
 * hyprbaric_native_layer_shell_monitor_target_to_string:
 * @object: a #HyprbaricNativeLayerShellMonitorTarget.
 *
 * Returns a string representation of a #HyprbaricNativeLayerShellMonitorTarget object.
 *
 * Returns: (transfer full): a new string, free with g_free().
 */
gchar* hyprbaric_native_layer_shell_monitor_target_to_string(HyprbaricNativeLayerShellMonitorTarget* object);

/**
 * HyprbaricNativeLayerShellMonitor:
 *
 */

G_DECLARE_FINAL_TYPE(HyprbaricNativeLayerShellMonitor, hyprbaric_native_layer_shell_monitor, HYPRBARIC, NATIVE_LAYER_SHELL_MONITOR, GObject)

/**
 * hyprbaric_native_layer_shell_monitor_new:
 * name: field in this object.
 * label: field in this object.
 * is_primary: field in this object.
 * x: field in this object.
 * y: field in this object.
 * width: field in this object.
 * height: field in this object.
 * refresh_rate_millihertz: field in this object.
 *
 * Creates a new #NativeLayerShellMonitor object.
 *
 * Returns: a new #HyprbaricNativeLayerShellMonitor
 */
HyprbaricNativeLayerShellMonitor* hyprbaric_native_layer_shell_monitor_new(const gchar* name, const gchar* label, gboolean is_primary, int64_t x, int64_t y, int64_t width, int64_t height, int64_t refresh_rate_millihertz);

/**
 * hyprbaric_native_layer_shell_monitor_get_name
 * @object: a #HyprbaricNativeLayerShellMonitor.
 *
 * Gets the value of the name field of @object.
 *
 * Returns: the field value.
 */
const gchar* hyprbaric_native_layer_shell_monitor_get_name(HyprbaricNativeLayerShellMonitor* object);

/**
 * hyprbaric_native_layer_shell_monitor_get_label
 * @object: a #HyprbaricNativeLayerShellMonitor.
 *
 * Gets the value of the label field of @object.
 *
 * Returns: the field value.
 */
const gchar* hyprbaric_native_layer_shell_monitor_get_label(HyprbaricNativeLayerShellMonitor* object);

/**
 * hyprbaric_native_layer_shell_monitor_get_is_primary
 * @object: a #HyprbaricNativeLayerShellMonitor.
 *
 * Gets the value of the isPrimary field of @object.
 *
 * Returns: the field value.
 */
gboolean hyprbaric_native_layer_shell_monitor_get_is_primary(HyprbaricNativeLayerShellMonitor* object);

/**
 * hyprbaric_native_layer_shell_monitor_get_x
 * @object: a #HyprbaricNativeLayerShellMonitor.
 *
 * Gets the value of the x field of @object.
 *
 * Returns: the field value.
 */
int64_t hyprbaric_native_layer_shell_monitor_get_x(HyprbaricNativeLayerShellMonitor* object);

/**
 * hyprbaric_native_layer_shell_monitor_get_y
 * @object: a #HyprbaricNativeLayerShellMonitor.
 *
 * Gets the value of the y field of @object.
 *
 * Returns: the field value.
 */
int64_t hyprbaric_native_layer_shell_monitor_get_y(HyprbaricNativeLayerShellMonitor* object);

/**
 * hyprbaric_native_layer_shell_monitor_get_width
 * @object: a #HyprbaricNativeLayerShellMonitor.
 *
 * Gets the value of the width field of @object.
 *
 * Returns: the field value.
 */
int64_t hyprbaric_native_layer_shell_monitor_get_width(HyprbaricNativeLayerShellMonitor* object);

/**
 * hyprbaric_native_layer_shell_monitor_get_height
 * @object: a #HyprbaricNativeLayerShellMonitor.
 *
 * Gets the value of the height field of @object.
 *
 * Returns: the field value.
 */
int64_t hyprbaric_native_layer_shell_monitor_get_height(HyprbaricNativeLayerShellMonitor* object);

/**
 * hyprbaric_native_layer_shell_monitor_get_refresh_rate_millihertz
 * @object: a #HyprbaricNativeLayerShellMonitor.
 *
 * Gets the value of the refreshRateMillihertz field of @object.
 *
 * Returns: the field value.
 */
int64_t hyprbaric_native_layer_shell_monitor_get_refresh_rate_millihertz(HyprbaricNativeLayerShellMonitor* object);

/**
 * hyprbaric_native_layer_shell_monitor_equals:
 * @a: a #HyprbaricNativeLayerShellMonitor.
 * @b: another #HyprbaricNativeLayerShellMonitor.
 *
 * Checks if two #HyprbaricNativeLayerShellMonitor objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean hyprbaric_native_layer_shell_monitor_equals(HyprbaricNativeLayerShellMonitor* a, HyprbaricNativeLayerShellMonitor* b);

/**
 * hyprbaric_native_layer_shell_monitor_hash:
 * @object: a #HyprbaricNativeLayerShellMonitor.
 *
 * Calculates a hash code for a #HyprbaricNativeLayerShellMonitor object.
 *
 * Returns: the hash code.
 */
guint hyprbaric_native_layer_shell_monitor_hash(HyprbaricNativeLayerShellMonitor* object);

/**
 * hyprbaric_native_layer_shell_monitor_to_string:
 * @object: a #HyprbaricNativeLayerShellMonitor.
 *
 * Returns a string representation of a #HyprbaricNativeLayerShellMonitor object.
 *
 * Returns: (transfer full): a new string, free with g_free().
 */
gchar* hyprbaric_native_layer_shell_monitor_to_string(HyprbaricNativeLayerShellMonitor* object);

/**
 * HyprbaricNativeLayerShellAnchors:
 *
 */

G_DECLARE_FINAL_TYPE(HyprbaricNativeLayerShellAnchors, hyprbaric_native_layer_shell_anchors, HYPRBARIC, NATIVE_LAYER_SHELL_ANCHORS, GObject)

/**
 * hyprbaric_native_layer_shell_anchors_new:
 * top: field in this object.
 * bottom: field in this object.
 * left: field in this object.
 * right: field in this object.
 *
 * Creates a new #NativeLayerShellAnchors object.
 *
 * Returns: a new #HyprbaricNativeLayerShellAnchors
 */
HyprbaricNativeLayerShellAnchors* hyprbaric_native_layer_shell_anchors_new(gboolean* top, gboolean* bottom, gboolean* left, gboolean* right);

/**
 * hyprbaric_native_layer_shell_anchors_get_top
 * @object: a #HyprbaricNativeLayerShellAnchors.
 *
 * Gets the value of the top field of @object.
 *
 * Returns: the field value.
 */
gboolean* hyprbaric_native_layer_shell_anchors_get_top(HyprbaricNativeLayerShellAnchors* object);

/**
 * hyprbaric_native_layer_shell_anchors_get_bottom
 * @object: a #HyprbaricNativeLayerShellAnchors.
 *
 * Gets the value of the bottom field of @object.
 *
 * Returns: the field value.
 */
gboolean* hyprbaric_native_layer_shell_anchors_get_bottom(HyprbaricNativeLayerShellAnchors* object);

/**
 * hyprbaric_native_layer_shell_anchors_get_left
 * @object: a #HyprbaricNativeLayerShellAnchors.
 *
 * Gets the value of the left field of @object.
 *
 * Returns: the field value.
 */
gboolean* hyprbaric_native_layer_shell_anchors_get_left(HyprbaricNativeLayerShellAnchors* object);

/**
 * hyprbaric_native_layer_shell_anchors_get_right
 * @object: a #HyprbaricNativeLayerShellAnchors.
 *
 * Gets the value of the right field of @object.
 *
 * Returns: the field value.
 */
gboolean* hyprbaric_native_layer_shell_anchors_get_right(HyprbaricNativeLayerShellAnchors* object);

/**
 * hyprbaric_native_layer_shell_anchors_equals:
 * @a: a #HyprbaricNativeLayerShellAnchors.
 * @b: another #HyprbaricNativeLayerShellAnchors.
 *
 * Checks if two #HyprbaricNativeLayerShellAnchors objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean hyprbaric_native_layer_shell_anchors_equals(HyprbaricNativeLayerShellAnchors* a, HyprbaricNativeLayerShellAnchors* b);

/**
 * hyprbaric_native_layer_shell_anchors_hash:
 * @object: a #HyprbaricNativeLayerShellAnchors.
 *
 * Calculates a hash code for a #HyprbaricNativeLayerShellAnchors object.
 *
 * Returns: the hash code.
 */
guint hyprbaric_native_layer_shell_anchors_hash(HyprbaricNativeLayerShellAnchors* object);

/**
 * hyprbaric_native_layer_shell_anchors_to_string:
 * @object: a #HyprbaricNativeLayerShellAnchors.
 *
 * Returns a string representation of a #HyprbaricNativeLayerShellAnchors object.
 *
 * Returns: (transfer full): a new string, free with g_free().
 */
gchar* hyprbaric_native_layer_shell_anchors_to_string(HyprbaricNativeLayerShellAnchors* object);

/**
 * HyprbaricNativeLayerShellMargins:
 *
 */

G_DECLARE_FINAL_TYPE(HyprbaricNativeLayerShellMargins, hyprbaric_native_layer_shell_margins, HYPRBARIC, NATIVE_LAYER_SHELL_MARGINS, GObject)

/**
 * hyprbaric_native_layer_shell_margins_new:
 * top: field in this object.
 * bottom: field in this object.
 * left: field in this object.
 * right: field in this object.
 *
 * Creates a new #NativeLayerShellMargins object.
 *
 * Returns: a new #HyprbaricNativeLayerShellMargins
 */
HyprbaricNativeLayerShellMargins* hyprbaric_native_layer_shell_margins_new(int64_t* top, int64_t* bottom, int64_t* left, int64_t* right);

/**
 * hyprbaric_native_layer_shell_margins_get_top
 * @object: a #HyprbaricNativeLayerShellMargins.
 *
 * Gets the value of the top field of @object.
 *
 * Returns: the field value.
 */
int64_t* hyprbaric_native_layer_shell_margins_get_top(HyprbaricNativeLayerShellMargins* object);

/**
 * hyprbaric_native_layer_shell_margins_get_bottom
 * @object: a #HyprbaricNativeLayerShellMargins.
 *
 * Gets the value of the bottom field of @object.
 *
 * Returns: the field value.
 */
int64_t* hyprbaric_native_layer_shell_margins_get_bottom(HyprbaricNativeLayerShellMargins* object);

/**
 * hyprbaric_native_layer_shell_margins_get_left
 * @object: a #HyprbaricNativeLayerShellMargins.
 *
 * Gets the value of the left field of @object.
 *
 * Returns: the field value.
 */
int64_t* hyprbaric_native_layer_shell_margins_get_left(HyprbaricNativeLayerShellMargins* object);

/**
 * hyprbaric_native_layer_shell_margins_get_right
 * @object: a #HyprbaricNativeLayerShellMargins.
 *
 * Gets the value of the right field of @object.
 *
 * Returns: the field value.
 */
int64_t* hyprbaric_native_layer_shell_margins_get_right(HyprbaricNativeLayerShellMargins* object);

/**
 * hyprbaric_native_layer_shell_margins_equals:
 * @a: a #HyprbaricNativeLayerShellMargins.
 * @b: another #HyprbaricNativeLayerShellMargins.
 *
 * Checks if two #HyprbaricNativeLayerShellMargins objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean hyprbaric_native_layer_shell_margins_equals(HyprbaricNativeLayerShellMargins* a, HyprbaricNativeLayerShellMargins* b);

/**
 * hyprbaric_native_layer_shell_margins_hash:
 * @object: a #HyprbaricNativeLayerShellMargins.
 *
 * Calculates a hash code for a #HyprbaricNativeLayerShellMargins object.
 *
 * Returns: the hash code.
 */
guint hyprbaric_native_layer_shell_margins_hash(HyprbaricNativeLayerShellMargins* object);

/**
 * hyprbaric_native_layer_shell_margins_to_string:
 * @object: a #HyprbaricNativeLayerShellMargins.
 *
 * Returns a string representation of a #HyprbaricNativeLayerShellMargins object.
 *
 * Returns: (transfer full): a new string, free with g_free().
 */
gchar* hyprbaric_native_layer_shell_margins_to_string(HyprbaricNativeLayerShellMargins* object);

/**
 * HyprbaricNativeLayerShellSize:
 *
 */

G_DECLARE_FINAL_TYPE(HyprbaricNativeLayerShellSize, hyprbaric_native_layer_shell_size, HYPRBARIC, NATIVE_LAYER_SHELL_SIZE, GObject)

/**
 * hyprbaric_native_layer_shell_size_new:
 * width: field in this object.
 * height: field in this object.
 *
 * Creates a new #NativeLayerShellSize object.
 *
 * Returns: a new #HyprbaricNativeLayerShellSize
 */
HyprbaricNativeLayerShellSize* hyprbaric_native_layer_shell_size_new(int64_t* width, int64_t* height);

/**
 * hyprbaric_native_layer_shell_size_get_width
 * @object: a #HyprbaricNativeLayerShellSize.
 *
 * Gets the value of the width field of @object.
 *
 * Returns: the field value.
 */
int64_t* hyprbaric_native_layer_shell_size_get_width(HyprbaricNativeLayerShellSize* object);

/**
 * hyprbaric_native_layer_shell_size_get_height
 * @object: a #HyprbaricNativeLayerShellSize.
 *
 * Gets the value of the height field of @object.
 *
 * Returns: the field value.
 */
int64_t* hyprbaric_native_layer_shell_size_get_height(HyprbaricNativeLayerShellSize* object);

/**
 * hyprbaric_native_layer_shell_size_equals:
 * @a: a #HyprbaricNativeLayerShellSize.
 * @b: another #HyprbaricNativeLayerShellSize.
 *
 * Checks if two #HyprbaricNativeLayerShellSize objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean hyprbaric_native_layer_shell_size_equals(HyprbaricNativeLayerShellSize* a, HyprbaricNativeLayerShellSize* b);

/**
 * hyprbaric_native_layer_shell_size_hash:
 * @object: a #HyprbaricNativeLayerShellSize.
 *
 * Calculates a hash code for a #HyprbaricNativeLayerShellSize object.
 *
 * Returns: the hash code.
 */
guint hyprbaric_native_layer_shell_size_hash(HyprbaricNativeLayerShellSize* object);

/**
 * hyprbaric_native_layer_shell_size_to_string:
 * @object: a #HyprbaricNativeLayerShellSize.
 *
 * Returns a string representation of a #HyprbaricNativeLayerShellSize object.
 *
 * Returns: (transfer full): a new string, free with g_free().
 */
gchar* hyprbaric_native_layer_shell_size_to_string(HyprbaricNativeLayerShellSize* object);

/**
 * HyprbaricNativeLayerShellRegion:
 *
 */

G_DECLARE_FINAL_TYPE(HyprbaricNativeLayerShellRegion, hyprbaric_native_layer_shell_region, HYPRBARIC, NATIVE_LAYER_SHELL_REGION, GObject)

/**
 * hyprbaric_native_layer_shell_region_new:
 * x: field in this object.
 * y: field in this object.
 * width: field in this object.
 * height: field in this object.
 * radius_top_left: field in this object.
 * radius_top_right: field in this object.
 * radius_bottom_right: field in this object.
 * radius_bottom_left: field in this object.
 *
 * Creates a new #NativeLayerShellRegion object.
 *
 * Returns: a new #HyprbaricNativeLayerShellRegion
 */
HyprbaricNativeLayerShellRegion* hyprbaric_native_layer_shell_region_new(int64_t x, int64_t y, int64_t width, int64_t height, int64_t radius_top_left, int64_t radius_top_right, int64_t radius_bottom_right, int64_t radius_bottom_left);

/**
 * hyprbaric_native_layer_shell_region_get_x
 * @object: a #HyprbaricNativeLayerShellRegion.
 *
 * Gets the value of the x field of @object.
 *
 * Returns: the field value.
 */
int64_t hyprbaric_native_layer_shell_region_get_x(HyprbaricNativeLayerShellRegion* object);

/**
 * hyprbaric_native_layer_shell_region_get_y
 * @object: a #HyprbaricNativeLayerShellRegion.
 *
 * Gets the value of the y field of @object.
 *
 * Returns: the field value.
 */
int64_t hyprbaric_native_layer_shell_region_get_y(HyprbaricNativeLayerShellRegion* object);

/**
 * hyprbaric_native_layer_shell_region_get_width
 * @object: a #HyprbaricNativeLayerShellRegion.
 *
 * Gets the value of the width field of @object.
 *
 * Returns: the field value.
 */
int64_t hyprbaric_native_layer_shell_region_get_width(HyprbaricNativeLayerShellRegion* object);

/**
 * hyprbaric_native_layer_shell_region_get_height
 * @object: a #HyprbaricNativeLayerShellRegion.
 *
 * Gets the value of the height field of @object.
 *
 * Returns: the field value.
 */
int64_t hyprbaric_native_layer_shell_region_get_height(HyprbaricNativeLayerShellRegion* object);

/**
 * hyprbaric_native_layer_shell_region_get_radius_top_left
 * @object: a #HyprbaricNativeLayerShellRegion.
 *
 * Gets the value of the radiusTopLeft field of @object.
 *
 * Returns: the field value.
 */
int64_t hyprbaric_native_layer_shell_region_get_radius_top_left(HyprbaricNativeLayerShellRegion* object);

/**
 * hyprbaric_native_layer_shell_region_get_radius_top_right
 * @object: a #HyprbaricNativeLayerShellRegion.
 *
 * Gets the value of the radiusTopRight field of @object.
 *
 * Returns: the field value.
 */
int64_t hyprbaric_native_layer_shell_region_get_radius_top_right(HyprbaricNativeLayerShellRegion* object);

/**
 * hyprbaric_native_layer_shell_region_get_radius_bottom_right
 * @object: a #HyprbaricNativeLayerShellRegion.
 *
 * Gets the value of the radiusBottomRight field of @object.
 *
 * Returns: the field value.
 */
int64_t hyprbaric_native_layer_shell_region_get_radius_bottom_right(HyprbaricNativeLayerShellRegion* object);

/**
 * hyprbaric_native_layer_shell_region_get_radius_bottom_left
 * @object: a #HyprbaricNativeLayerShellRegion.
 *
 * Gets the value of the radiusBottomLeft field of @object.
 *
 * Returns: the field value.
 */
int64_t hyprbaric_native_layer_shell_region_get_radius_bottom_left(HyprbaricNativeLayerShellRegion* object);

/**
 * hyprbaric_native_layer_shell_region_equals:
 * @a: a #HyprbaricNativeLayerShellRegion.
 * @b: another #HyprbaricNativeLayerShellRegion.
 *
 * Checks if two #HyprbaricNativeLayerShellRegion objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean hyprbaric_native_layer_shell_region_equals(HyprbaricNativeLayerShellRegion* a, HyprbaricNativeLayerShellRegion* b);

/**
 * hyprbaric_native_layer_shell_region_hash:
 * @object: a #HyprbaricNativeLayerShellRegion.
 *
 * Calculates a hash code for a #HyprbaricNativeLayerShellRegion object.
 *
 * Returns: the hash code.
 */
guint hyprbaric_native_layer_shell_region_hash(HyprbaricNativeLayerShellRegion* object);

/**
 * hyprbaric_native_layer_shell_region_to_string:
 * @object: a #HyprbaricNativeLayerShellRegion.
 *
 * Returns a string representation of a #HyprbaricNativeLayerShellRegion object.
 *
 * Returns: (transfer full): a new string, free with g_free().
 */
gchar* hyprbaric_native_layer_shell_region_to_string(HyprbaricNativeLayerShellRegion* object);

/**
 * HyprbaricNativeLayerShellRegionRequest:
 *
 */

G_DECLARE_FINAL_TYPE(HyprbaricNativeLayerShellRegionRequest, hyprbaric_native_layer_shell_region_request, HYPRBARIC, NATIVE_LAYER_SHELL_REGION_REQUEST, GObject)

/**
 * hyprbaric_native_layer_shell_region_request_new:
 * bar_height: field in this object.
 * bar_edge: field in this object.
 * menu: field in this object.
 * passive_regions: field in this object.
 * capture_all_clicks: field in this object.
 *
 * Creates a new #NativeLayerShellRegionRequest object.
 *
 * Returns: a new #HyprbaricNativeLayerShellRegionRequest
 */
HyprbaricNativeLayerShellRegionRequest* hyprbaric_native_layer_shell_region_request_new(int64_t bar_height, HyprbaricNativeLayerShellBarEdge bar_edge, HyprbaricNativeLayerShellRegion* menu, FlValue* passive_regions, gboolean capture_all_clicks);

/**
 * hyprbaric_native_layer_shell_region_request_get_bar_height
 * @object: a #HyprbaricNativeLayerShellRegionRequest.
 *
 * Gets the value of the barHeight field of @object.
 *
 * Returns: the field value.
 */
int64_t hyprbaric_native_layer_shell_region_request_get_bar_height(HyprbaricNativeLayerShellRegionRequest* object);

/**
 * hyprbaric_native_layer_shell_region_request_get_bar_edge
 * @object: a #HyprbaricNativeLayerShellRegionRequest.
 *
 * Gets the value of the barEdge field of @object.
 *
 * Returns: the field value.
 */
HyprbaricNativeLayerShellBarEdge hyprbaric_native_layer_shell_region_request_get_bar_edge(HyprbaricNativeLayerShellRegionRequest* object);

/**
 * hyprbaric_native_layer_shell_region_request_get_menu
 * @object: a #HyprbaricNativeLayerShellRegionRequest.
 *
 * Gets the value of the menu field of @object.
 *
 * Returns: the field value.
 */
HyprbaricNativeLayerShellRegion* hyprbaric_native_layer_shell_region_request_get_menu(HyprbaricNativeLayerShellRegionRequest* object);

/**
 * hyprbaric_native_layer_shell_region_request_get_passive_regions
 * @object: a #HyprbaricNativeLayerShellRegionRequest.
 *
 * Gets the value of the passiveRegions field of @object.
 *
 * Returns: the field value.
 */
FlValue* hyprbaric_native_layer_shell_region_request_get_passive_regions(HyprbaricNativeLayerShellRegionRequest* object);

/**
 * hyprbaric_native_layer_shell_region_request_get_capture_all_clicks
 * @object: a #HyprbaricNativeLayerShellRegionRequest.
 *
 * Gets the value of the captureAllClicks field of @object.
 *
 * Returns: the field value.
 */
gboolean hyprbaric_native_layer_shell_region_request_get_capture_all_clicks(HyprbaricNativeLayerShellRegionRequest* object);

/**
 * hyprbaric_native_layer_shell_region_request_equals:
 * @a: a #HyprbaricNativeLayerShellRegionRequest.
 * @b: another #HyprbaricNativeLayerShellRegionRequest.
 *
 * Checks if two #HyprbaricNativeLayerShellRegionRequest objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean hyprbaric_native_layer_shell_region_request_equals(HyprbaricNativeLayerShellRegionRequest* a, HyprbaricNativeLayerShellRegionRequest* b);

/**
 * hyprbaric_native_layer_shell_region_request_hash:
 * @object: a #HyprbaricNativeLayerShellRegionRequest.
 *
 * Calculates a hash code for a #HyprbaricNativeLayerShellRegionRequest object.
 *
 * Returns: the hash code.
 */
guint hyprbaric_native_layer_shell_region_request_hash(HyprbaricNativeLayerShellRegionRequest* object);

/**
 * hyprbaric_native_layer_shell_region_request_to_string:
 * @object: a #HyprbaricNativeLayerShellRegionRequest.
 *
 * Returns a string representation of a #HyprbaricNativeLayerShellRegionRequest object.
 *
 * Returns: (transfer full): a new string, free with g_free().
 */
gchar* hyprbaric_native_layer_shell_region_request_to_string(HyprbaricNativeLayerShellRegionRequest* object);

/**
 * HyprbaricNativeLayerShellPanelConfig:
 *
 */

G_DECLARE_FINAL_TYPE(HyprbaricNativeLayerShellPanelConfig, hyprbaric_native_layer_shell_panel_config, HYPRBARIC, NATIVE_LAYER_SHELL_PANEL_CONFIG, GObject)

/**
 * hyprbaric_native_layer_shell_panel_config_new:
 * app_namespace: field in this object.
 * layer: field in this object.
 * anchors: field in this object.
 * margins: field in this object.
 * size: field in this object.
 * exclusive_zone: field in this object.
 * auto_exclusive_zone: field in this object.
 * keyboard_mode: field in this object.
 * monitor: field in this object.
 *
 * Creates a new #NativeLayerShellPanelConfig object.
 *
 * Returns: a new #HyprbaricNativeLayerShellPanelConfig
 */
HyprbaricNativeLayerShellPanelConfig* hyprbaric_native_layer_shell_panel_config_new(const gchar* app_namespace, HyprbaricNativeLayerShellLayer layer, HyprbaricNativeLayerShellAnchors* anchors, HyprbaricNativeLayerShellMargins* margins, HyprbaricNativeLayerShellSize* size, int64_t exclusive_zone, gboolean auto_exclusive_zone, HyprbaricNativeLayerShellKeyboardMode keyboard_mode, HyprbaricNativeLayerShellMonitorTarget* monitor);

/**
 * hyprbaric_native_layer_shell_panel_config_get_app_namespace
 * @object: a #HyprbaricNativeLayerShellPanelConfig.
 *
 * Gets the value of the appNamespace field of @object.
 *
 * Returns: the field value.
 */
const gchar* hyprbaric_native_layer_shell_panel_config_get_app_namespace(HyprbaricNativeLayerShellPanelConfig* object);

/**
 * hyprbaric_native_layer_shell_panel_config_get_layer
 * @object: a #HyprbaricNativeLayerShellPanelConfig.
 *
 * Gets the value of the layer field of @object.
 *
 * Returns: the field value.
 */
HyprbaricNativeLayerShellLayer hyprbaric_native_layer_shell_panel_config_get_layer(HyprbaricNativeLayerShellPanelConfig* object);

/**
 * hyprbaric_native_layer_shell_panel_config_get_anchors
 * @object: a #HyprbaricNativeLayerShellPanelConfig.
 *
 * Gets the value of the anchors field of @object.
 *
 * Returns: the field value.
 */
HyprbaricNativeLayerShellAnchors* hyprbaric_native_layer_shell_panel_config_get_anchors(HyprbaricNativeLayerShellPanelConfig* object);

/**
 * hyprbaric_native_layer_shell_panel_config_get_margins
 * @object: a #HyprbaricNativeLayerShellPanelConfig.
 *
 * Gets the value of the margins field of @object.
 *
 * Returns: the field value.
 */
HyprbaricNativeLayerShellMargins* hyprbaric_native_layer_shell_panel_config_get_margins(HyprbaricNativeLayerShellPanelConfig* object);

/**
 * hyprbaric_native_layer_shell_panel_config_get_size
 * @object: a #HyprbaricNativeLayerShellPanelConfig.
 *
 * Gets the value of the size field of @object.
 *
 * Returns: the field value.
 */
HyprbaricNativeLayerShellSize* hyprbaric_native_layer_shell_panel_config_get_size(HyprbaricNativeLayerShellPanelConfig* object);

/**
 * hyprbaric_native_layer_shell_panel_config_get_exclusive_zone
 * @object: a #HyprbaricNativeLayerShellPanelConfig.
 *
 * Gets the value of the exclusiveZone field of @object.
 *
 * Returns: the field value.
 */
int64_t hyprbaric_native_layer_shell_panel_config_get_exclusive_zone(HyprbaricNativeLayerShellPanelConfig* object);

/**
 * hyprbaric_native_layer_shell_panel_config_get_auto_exclusive_zone
 * @object: a #HyprbaricNativeLayerShellPanelConfig.
 *
 * Gets the value of the autoExclusiveZone field of @object.
 *
 * Returns: the field value.
 */
gboolean hyprbaric_native_layer_shell_panel_config_get_auto_exclusive_zone(HyprbaricNativeLayerShellPanelConfig* object);

/**
 * hyprbaric_native_layer_shell_panel_config_get_keyboard_mode
 * @object: a #HyprbaricNativeLayerShellPanelConfig.
 *
 * Gets the value of the keyboardMode field of @object.
 *
 * Returns: the field value.
 */
HyprbaricNativeLayerShellKeyboardMode hyprbaric_native_layer_shell_panel_config_get_keyboard_mode(HyprbaricNativeLayerShellPanelConfig* object);

/**
 * hyprbaric_native_layer_shell_panel_config_get_monitor
 * @object: a #HyprbaricNativeLayerShellPanelConfig.
 *
 * Gets the value of the monitor field of @object.
 *
 * Returns: the field value.
 */
HyprbaricNativeLayerShellMonitorTarget* hyprbaric_native_layer_shell_panel_config_get_monitor(HyprbaricNativeLayerShellPanelConfig* object);

/**
 * hyprbaric_native_layer_shell_panel_config_equals:
 * @a: a #HyprbaricNativeLayerShellPanelConfig.
 * @b: another #HyprbaricNativeLayerShellPanelConfig.
 *
 * Checks if two #HyprbaricNativeLayerShellPanelConfig objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean hyprbaric_native_layer_shell_panel_config_equals(HyprbaricNativeLayerShellPanelConfig* a, HyprbaricNativeLayerShellPanelConfig* b);

/**
 * hyprbaric_native_layer_shell_panel_config_hash:
 * @object: a #HyprbaricNativeLayerShellPanelConfig.
 *
 * Calculates a hash code for a #HyprbaricNativeLayerShellPanelConfig object.
 *
 * Returns: the hash code.
 */
guint hyprbaric_native_layer_shell_panel_config_hash(HyprbaricNativeLayerShellPanelConfig* object);

/**
 * hyprbaric_native_layer_shell_panel_config_to_string:
 * @object: a #HyprbaricNativeLayerShellPanelConfig.
 *
 * Returns a string representation of a #HyprbaricNativeLayerShellPanelConfig object.
 *
 * Returns: (transfer full): a new string, free with g_free().
 */
gchar* hyprbaric_native_layer_shell_panel_config_to_string(HyprbaricNativeLayerShellPanelConfig* object);

G_DECLARE_FINAL_TYPE(HyprbaricMessageCodec, hyprbaric_message_codec, HYPRBARIC, MESSAGE_CODEC, FlStandardMessageCodec)

/**
 * Custom type ID constants:
 *
 * Constants used to identify custom types in the codec.
 * They are used in the codec to encode and decode custom types.
 * They may be used in custom object creation functions to identify the type.
 */
extern const int hyprbaric_native_layer_shell_layer_type_id;
extern const int hyprbaric_native_layer_shell_keyboard_mode_type_id;
extern const int hyprbaric_native_layer_shell_bar_edge_type_id;
extern const int hyprbaric_native_layer_shell_monitor_target_kind_type_id;
extern const int hyprbaric_native_layer_shell_monitor_target_type_id;
extern const int hyprbaric_native_layer_shell_monitor_type_id;
extern const int hyprbaric_native_layer_shell_anchors_type_id;
extern const int hyprbaric_native_layer_shell_margins_type_id;
extern const int hyprbaric_native_layer_shell_size_type_id;
extern const int hyprbaric_native_layer_shell_region_type_id;
extern const int hyprbaric_native_layer_shell_region_request_type_id;
extern const int hyprbaric_native_layer_shell_panel_config_type_id;

G_DECLARE_FINAL_TYPE(HyprbaricNativeLayerShellHostApi, hyprbaric_native_layer_shell_host_api, HYPRBARIC, NATIVE_LAYER_SHELL_HOST_API, GObject)

G_DECLARE_FINAL_TYPE(HyprbaricNativeLayerShellHostApiListMonitorsResponse, hyprbaric_native_layer_shell_host_api_list_monitors_response, HYPRBARIC, NATIVE_LAYER_SHELL_HOST_API_LIST_MONITORS_RESPONSE, GObject)

/**
 * hyprbaric_native_layer_shell_host_api_list_monitors_response_new:
 *
 * Creates a new response to NativeLayerShellHostApi.listMonitors.
 *
 * Returns: a new #HyprbaricNativeLayerShellHostApiListMonitorsResponse
 */
HyprbaricNativeLayerShellHostApiListMonitorsResponse* hyprbaric_native_layer_shell_host_api_list_monitors_response_new(FlValue* return_value);

/**
 * hyprbaric_native_layer_shell_host_api_list_monitors_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to NativeLayerShellHostApi.listMonitors.
 *
 * Returns: a new #HyprbaricNativeLayerShellHostApiListMonitorsResponse
 */
HyprbaricNativeLayerShellHostApiListMonitorsResponse* hyprbaric_native_layer_shell_host_api_list_monitors_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(HyprbaricNativeLayerShellHostApiCurrentMonitorResponse, hyprbaric_native_layer_shell_host_api_current_monitor_response, HYPRBARIC, NATIVE_LAYER_SHELL_HOST_API_CURRENT_MONITOR_RESPONSE, GObject)

/**
 * hyprbaric_native_layer_shell_host_api_current_monitor_response_new:
 *
 * Creates a new response to NativeLayerShellHostApi.currentMonitor.
 *
 * Returns: a new #HyprbaricNativeLayerShellHostApiCurrentMonitorResponse
 */
HyprbaricNativeLayerShellHostApiCurrentMonitorResponse* hyprbaric_native_layer_shell_host_api_current_monitor_response_new(HyprbaricNativeLayerShellMonitor* return_value);

/**
 * hyprbaric_native_layer_shell_host_api_current_monitor_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to NativeLayerShellHostApi.currentMonitor.
 *
 * Returns: a new #HyprbaricNativeLayerShellHostApiCurrentMonitorResponse
 */
HyprbaricNativeLayerShellHostApiCurrentMonitorResponse* hyprbaric_native_layer_shell_host_api_current_monitor_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(HyprbaricNativeLayerShellHostApiConfigurePanelResponse, hyprbaric_native_layer_shell_host_api_configure_panel_response, HYPRBARIC, NATIVE_LAYER_SHELL_HOST_API_CONFIGURE_PANEL_RESPONSE, GObject)

/**
 * hyprbaric_native_layer_shell_host_api_configure_panel_response_new:
 *
 * Creates a new response to NativeLayerShellHostApi.configurePanel.
 *
 * Returns: a new #HyprbaricNativeLayerShellHostApiConfigurePanelResponse
 */
HyprbaricNativeLayerShellHostApiConfigurePanelResponse* hyprbaric_native_layer_shell_host_api_configure_panel_response_new();

/**
 * hyprbaric_native_layer_shell_host_api_configure_panel_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to NativeLayerShellHostApi.configurePanel.
 *
 * Returns: a new #HyprbaricNativeLayerShellHostApiConfigurePanelResponse
 */
HyprbaricNativeLayerShellHostApiConfigurePanelResponse* hyprbaric_native_layer_shell_host_api_configure_panel_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(HyprbaricNativeLayerShellHostApiSetLayerResponse, hyprbaric_native_layer_shell_host_api_set_layer_response, HYPRBARIC, NATIVE_LAYER_SHELL_HOST_API_SET_LAYER_RESPONSE, GObject)

/**
 * hyprbaric_native_layer_shell_host_api_set_layer_response_new:
 *
 * Creates a new response to NativeLayerShellHostApi.setLayer.
 *
 * Returns: a new #HyprbaricNativeLayerShellHostApiSetLayerResponse
 */
HyprbaricNativeLayerShellHostApiSetLayerResponse* hyprbaric_native_layer_shell_host_api_set_layer_response_new();

/**
 * hyprbaric_native_layer_shell_host_api_set_layer_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to NativeLayerShellHostApi.setLayer.
 *
 * Returns: a new #HyprbaricNativeLayerShellHostApiSetLayerResponse
 */
HyprbaricNativeLayerShellHostApiSetLayerResponse* hyprbaric_native_layer_shell_host_api_set_layer_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(HyprbaricNativeLayerShellHostApiSetNamespaceResponse, hyprbaric_native_layer_shell_host_api_set_namespace_response, HYPRBARIC, NATIVE_LAYER_SHELL_HOST_API_SET_NAMESPACE_RESPONSE, GObject)

/**
 * hyprbaric_native_layer_shell_host_api_set_namespace_response_new:
 *
 * Creates a new response to NativeLayerShellHostApi.setNamespace.
 *
 * Returns: a new #HyprbaricNativeLayerShellHostApiSetNamespaceResponse
 */
HyprbaricNativeLayerShellHostApiSetNamespaceResponse* hyprbaric_native_layer_shell_host_api_set_namespace_response_new();

/**
 * hyprbaric_native_layer_shell_host_api_set_namespace_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to NativeLayerShellHostApi.setNamespace.
 *
 * Returns: a new #HyprbaricNativeLayerShellHostApiSetNamespaceResponse
 */
HyprbaricNativeLayerShellHostApiSetNamespaceResponse* hyprbaric_native_layer_shell_host_api_set_namespace_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(HyprbaricNativeLayerShellHostApiSetAnchorsResponse, hyprbaric_native_layer_shell_host_api_set_anchors_response, HYPRBARIC, NATIVE_LAYER_SHELL_HOST_API_SET_ANCHORS_RESPONSE, GObject)

/**
 * hyprbaric_native_layer_shell_host_api_set_anchors_response_new:
 *
 * Creates a new response to NativeLayerShellHostApi.setAnchors.
 *
 * Returns: a new #HyprbaricNativeLayerShellHostApiSetAnchorsResponse
 */
HyprbaricNativeLayerShellHostApiSetAnchorsResponse* hyprbaric_native_layer_shell_host_api_set_anchors_response_new();

/**
 * hyprbaric_native_layer_shell_host_api_set_anchors_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to NativeLayerShellHostApi.setAnchors.
 *
 * Returns: a new #HyprbaricNativeLayerShellHostApiSetAnchorsResponse
 */
HyprbaricNativeLayerShellHostApiSetAnchorsResponse* hyprbaric_native_layer_shell_host_api_set_anchors_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(HyprbaricNativeLayerShellHostApiSetMarginsResponse, hyprbaric_native_layer_shell_host_api_set_margins_response, HYPRBARIC, NATIVE_LAYER_SHELL_HOST_API_SET_MARGINS_RESPONSE, GObject)

/**
 * hyprbaric_native_layer_shell_host_api_set_margins_response_new:
 *
 * Creates a new response to NativeLayerShellHostApi.setMargins.
 *
 * Returns: a new #HyprbaricNativeLayerShellHostApiSetMarginsResponse
 */
HyprbaricNativeLayerShellHostApiSetMarginsResponse* hyprbaric_native_layer_shell_host_api_set_margins_response_new();

/**
 * hyprbaric_native_layer_shell_host_api_set_margins_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to NativeLayerShellHostApi.setMargins.
 *
 * Returns: a new #HyprbaricNativeLayerShellHostApiSetMarginsResponse
 */
HyprbaricNativeLayerShellHostApiSetMarginsResponse* hyprbaric_native_layer_shell_host_api_set_margins_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(HyprbaricNativeLayerShellHostApiSetExclusiveZoneResponse, hyprbaric_native_layer_shell_host_api_set_exclusive_zone_response, HYPRBARIC, NATIVE_LAYER_SHELL_HOST_API_SET_EXCLUSIVE_ZONE_RESPONSE, GObject)

/**
 * hyprbaric_native_layer_shell_host_api_set_exclusive_zone_response_new:
 *
 * Creates a new response to NativeLayerShellHostApi.setExclusiveZone.
 *
 * Returns: a new #HyprbaricNativeLayerShellHostApiSetExclusiveZoneResponse
 */
HyprbaricNativeLayerShellHostApiSetExclusiveZoneResponse* hyprbaric_native_layer_shell_host_api_set_exclusive_zone_response_new();

/**
 * hyprbaric_native_layer_shell_host_api_set_exclusive_zone_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to NativeLayerShellHostApi.setExclusiveZone.
 *
 * Returns: a new #HyprbaricNativeLayerShellHostApiSetExclusiveZoneResponse
 */
HyprbaricNativeLayerShellHostApiSetExclusiveZoneResponse* hyprbaric_native_layer_shell_host_api_set_exclusive_zone_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(HyprbaricNativeLayerShellHostApiSetAutoExclusiveZoneResponse, hyprbaric_native_layer_shell_host_api_set_auto_exclusive_zone_response, HYPRBARIC, NATIVE_LAYER_SHELL_HOST_API_SET_AUTO_EXCLUSIVE_ZONE_RESPONSE, GObject)

/**
 * hyprbaric_native_layer_shell_host_api_set_auto_exclusive_zone_response_new:
 *
 * Creates a new response to NativeLayerShellHostApi.setAutoExclusiveZone.
 *
 * Returns: a new #HyprbaricNativeLayerShellHostApiSetAutoExclusiveZoneResponse
 */
HyprbaricNativeLayerShellHostApiSetAutoExclusiveZoneResponse* hyprbaric_native_layer_shell_host_api_set_auto_exclusive_zone_response_new();

/**
 * hyprbaric_native_layer_shell_host_api_set_auto_exclusive_zone_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to NativeLayerShellHostApi.setAutoExclusiveZone.
 *
 * Returns: a new #HyprbaricNativeLayerShellHostApiSetAutoExclusiveZoneResponse
 */
HyprbaricNativeLayerShellHostApiSetAutoExclusiveZoneResponse* hyprbaric_native_layer_shell_host_api_set_auto_exclusive_zone_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(HyprbaricNativeLayerShellHostApiSetKeyboardModeResponse, hyprbaric_native_layer_shell_host_api_set_keyboard_mode_response, HYPRBARIC, NATIVE_LAYER_SHELL_HOST_API_SET_KEYBOARD_MODE_RESPONSE, GObject)

/**
 * hyprbaric_native_layer_shell_host_api_set_keyboard_mode_response_new:
 *
 * Creates a new response to NativeLayerShellHostApi.setKeyboardMode.
 *
 * Returns: a new #HyprbaricNativeLayerShellHostApiSetKeyboardModeResponse
 */
HyprbaricNativeLayerShellHostApiSetKeyboardModeResponse* hyprbaric_native_layer_shell_host_api_set_keyboard_mode_response_new();

/**
 * hyprbaric_native_layer_shell_host_api_set_keyboard_mode_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to NativeLayerShellHostApi.setKeyboardMode.
 *
 * Returns: a new #HyprbaricNativeLayerShellHostApiSetKeyboardModeResponse
 */
HyprbaricNativeLayerShellHostApiSetKeyboardModeResponse* hyprbaric_native_layer_shell_host_api_set_keyboard_mode_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(HyprbaricNativeLayerShellHostApiSetSizeResponse, hyprbaric_native_layer_shell_host_api_set_size_response, HYPRBARIC, NATIVE_LAYER_SHELL_HOST_API_SET_SIZE_RESPONSE, GObject)

/**
 * hyprbaric_native_layer_shell_host_api_set_size_response_new:
 *
 * Creates a new response to NativeLayerShellHostApi.setSize.
 *
 * Returns: a new #HyprbaricNativeLayerShellHostApiSetSizeResponse
 */
HyprbaricNativeLayerShellHostApiSetSizeResponse* hyprbaric_native_layer_shell_host_api_set_size_response_new();

/**
 * hyprbaric_native_layer_shell_host_api_set_size_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to NativeLayerShellHostApi.setSize.
 *
 * Returns: a new #HyprbaricNativeLayerShellHostApiSetSizeResponse
 */
HyprbaricNativeLayerShellHostApiSetSizeResponse* hyprbaric_native_layer_shell_host_api_set_size_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(HyprbaricNativeLayerShellHostApiSetRegionResponse, hyprbaric_native_layer_shell_host_api_set_region_response, HYPRBARIC, NATIVE_LAYER_SHELL_HOST_API_SET_REGION_RESPONSE, GObject)

/**
 * hyprbaric_native_layer_shell_host_api_set_region_response_new:
 *
 * Creates a new response to NativeLayerShellHostApi.setRegion.
 *
 * Returns: a new #HyprbaricNativeLayerShellHostApiSetRegionResponse
 */
HyprbaricNativeLayerShellHostApiSetRegionResponse* hyprbaric_native_layer_shell_host_api_set_region_response_new();

/**
 * hyprbaric_native_layer_shell_host_api_set_region_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to NativeLayerShellHostApi.setRegion.
 *
 * Returns: a new #HyprbaricNativeLayerShellHostApiSetRegionResponse
 */
HyprbaricNativeLayerShellHostApiSetRegionResponse* hyprbaric_native_layer_shell_host_api_set_region_response_new_error(const gchar* code, const gchar* message, FlValue* details);

/**
 * HyprbaricNativeLayerShellHostApiVTable:
 *
 * Table of functions exposed by NativeLayerShellHostApi to be implemented by the API provider.
 */
typedef struct {
  HyprbaricNativeLayerShellHostApiListMonitorsResponse* (*list_monitors)(gpointer user_data);
  HyprbaricNativeLayerShellHostApiCurrentMonitorResponse* (*current_monitor)(gpointer user_data);
  HyprbaricNativeLayerShellHostApiConfigurePanelResponse* (*configure_panel)(HyprbaricNativeLayerShellPanelConfig* config, gpointer user_data);
  HyprbaricNativeLayerShellHostApiSetLayerResponse* (*set_layer)(HyprbaricNativeLayerShellLayer layer, gpointer user_data);
  HyprbaricNativeLayerShellHostApiSetNamespaceResponse* (*set_namespace)(const gchar* app_namespace, gpointer user_data);
  HyprbaricNativeLayerShellHostApiSetAnchorsResponse* (*set_anchors)(HyprbaricNativeLayerShellAnchors* anchors, gpointer user_data);
  HyprbaricNativeLayerShellHostApiSetMarginsResponse* (*set_margins)(HyprbaricNativeLayerShellMargins* margins, gpointer user_data);
  HyprbaricNativeLayerShellHostApiSetExclusiveZoneResponse* (*set_exclusive_zone)(int64_t zone, gpointer user_data);
  HyprbaricNativeLayerShellHostApiSetAutoExclusiveZoneResponse* (*set_auto_exclusive_zone)(gboolean enabled, gpointer user_data);
  HyprbaricNativeLayerShellHostApiSetKeyboardModeResponse* (*set_keyboard_mode)(HyprbaricNativeLayerShellKeyboardMode mode, gpointer user_data);
  HyprbaricNativeLayerShellHostApiSetSizeResponse* (*set_size)(HyprbaricNativeLayerShellSize* size, gpointer user_data);
  HyprbaricNativeLayerShellHostApiSetRegionResponse* (*set_region)(HyprbaricNativeLayerShellRegionRequest* request, gpointer user_data);
} HyprbaricNativeLayerShellHostApiVTable;

/**
 * hyprbaric_native_layer_shell_host_api_set_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 * @vtable: implementations of the methods in this API.
 * @user_data: (closure): user data to pass to the functions in @vtable.
 * @user_data_free_func: (allow-none): a function which gets called to free @user_data, or %NULL.
 *
 * Connects the method handlers in the NativeLayerShellHostApi API.
 */
void hyprbaric_native_layer_shell_host_api_set_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix, const HyprbaricNativeLayerShellHostApiVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func);

/**
 * hyprbaric_native_layer_shell_host_api_clear_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 *
 * Clears the method handlers in the NativeLayerShellHostApi API.
 */
void hyprbaric_native_layer_shell_host_api_clear_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix);

G_END_DECLS

#endif  // PIGEON_LAYER_SHELL_API_G_H_
